linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages: []
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      #- github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    line-length: 100
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  godox:
    # Default: ["TODO", "BUG", "FIXME"]
    keywords:
      - BUG
      - FIXME
  funlen:
    # Default: 60
    lines: 80
  wrapcheck:
    ignoreSigs:
      - ".Errorf("
      - "errors.New("
      - "errors.Unwrap("
      - ".Wrap("
      - ".Wrapf("
      - ".WithMessage("
      - ".WithMessagef("
      - ".WithStack("
      - "merry.Prepend("
      - "merry.Append("
      - "merry.New("
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 15
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 0.3

issues:
  new-from-rev: origin/develop

linters:
  enable-all: true
  disable:
    - golint # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - paralleltest
    - maligned
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - unparam
    - ireturn
    - gci
    - gomoddirectives
    - tagliatelle

run:
  go: "1.19"
  deadline: 5m
  modules-download-mode: vendor
  skip-files:
    - "allocator.go"

