version: '3'
services:
  pg:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=stroppy
      - POSTGRES_USER=stroppy
      - POSTGRES_DB=stroppy
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./_data/postgres.db:/var/lib/postgresql/data/pgdata

  fdb:
    image: foundationdb/foundationdb:6.3.23
    environment:
      - FDB_COORDINATOR=fdb
      - FDB_COORDINATOR_PORT=4500
      - FDB_NETWORKING_MODE=container
    ports:
      - 4500:4500

  cdb:
    image: cockroachdb/cockroach:latest
    volumes:
      - ./data/cockroach/cockroach-data
    command:
      - "start-single-node"
      - "--insecure"
    ports:
      - "26257:26257"

  mongo:
    image: docker.binary.picodata.io/stroppy-mongodb:4.4.7
    command:
      - "--replSet"
      - "rs"
    ports:
      - "27017:27017"
