Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 4
    end
  
  
    config.vm.define:master do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "master"
      master.vm.network :private_network, ip: "172.16.1.10"
      master.vm.provision :shell, privileged: false, inline: $commands_set
      master.vm.provision :shell, privileged: false, path: "master.sh"
      config.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
      master.vm.synced_folder '../../../deploy_dev', '/home/vagrant/deploy_dev'
    end
  
    config.vm.define:worker_1 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-1"
      master.vm.network :private_network, ip: "172.16.1.11"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
    config.vm.define:worker_2 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-2"
      master.vm.network :private_network, ip: "172.16.1.12"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
    config.vm.define:worker_3 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-3"
      master.vm.network :private_network, ip: "172.16.1.13"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
    config.vm.define:worker_4 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-4"
      master.vm.network :private_network, ip: "172.16.1.14"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
    config.vm.define:worker_5 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-5"
      master.vm.network :private_network, ip: "172.16.1.15"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
    config.vm.define:worker_6 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-6"
      master.vm.network :private_network, ip: "172.16.1.16"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
    config.vm.define:worker_7 do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "worker-7"
      master.vm.network :private_network, ip: "172.16.1.17"
      config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      master.vm.provision :shell, privileged: false, inline: $commands_set
    end
  
  end
  
  $commands_set = <<-SHELL
  sudo sed -i "s/PasswordAuthentication.*/PasswordAuthentication yes/g" /etc/ssh/sshd_config
  sudo systemctl restart sshd
  cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
