apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: fdb-cont-kill-second
  namespace: default
  labels: null
  annotations: null
spec:
  selector:
    namespaces:
      - default
    pods:
      default:
        - sample-cluster-storage-1
        - sample-cluster-storage-2
        - sample-cluster-storage-3
  scheduler:
    cron: '*/2 * * * *'
  action: container-kill
  mode: one
  value: ''
  duration: 2s
  containerName: foundationdb
  gracePeriod: 0
