apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pg-pod-kill-first
  namespace: default
  labels: null
  annotations: null
spec:
  selector:
    namespaces:
      - default
    pods:
      default:
        - acid-postgres-cluster-0
        - acid-postgres-cluster-1
        - acid-postgres-cluster-2
  scheduler:
    cron: '*/2 * * * *'
  action: pod-kill
  mode: one
  value: ''
  duration: 1s
  containerName: ''
  gracePeriod: 0
