---
- hosts: nodes
  become: true
  roles:
  - cloudalchemy.node_exporter
  vars:
  tasks:
  - name: Install additional soft
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - unzip
      - zip

  - name: Restart rsyslog service
    systemd:
      name: rsyslog.service
      state: restarted
      daemon_reload: yes
      enabled: yes
      masked: no

  - name: Download Promtail and put in /usr/local/bin
    ansible.builtin.unarchive:
      src: https://github.com/grafana/loki/releases/download/v2.1.0/promtail-linux-amd64.zip
      dest: /usr/local/bin/
      remote_src: yes

  - name: Touch promtail-local-config.yaml in /etc/
    ansible.builtin.file:
      path: /etc/promtail-local-config.yaml
      state: touch
      owner: root
      group: root
      mode: '0640'

  - name: Add config in /etc/promtail-local-config.yaml
    blockinfile:
      path: /etc/promtail-local-config.yaml
      block: |2
          server:
            http_listen_port: 9080
            grpc_listen_port: 0

          positions:
            filename: /tmp/positions.yaml

          clients:
            - url: http://192.168.99.98:3100/loki/api/v1/push

          scrape_configs:
          - job_name: system
            static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*log

  - name: Touch /etc/systemd/system/promtail.service
    ansible.builtin.file:
      path: /etc/systemd/system/promtail.service
      state: touch
      owner: root
      group: root
      mode: '0644'

  - name: Add content to Promtail systemd unit
    blockinfile:
      path: /etc/systemd/system/promtail.service
      block: |2
          [Unit]
          Description=Promtail service
          After=network.target

          [Service]
          Type=simple
          User=root
          ExecStart=/usr/local/bin/promtail-linux-amd64 -config.file /etc/promtail-local-config.yaml

          [Install]
          WantedBy=multi-user.target

  - name: Restart Promtail service
    systemd:
      name: promtail.service
      state: restarted
      daemon_reload: yes
      enabled: yes
      masked: no
