name: BuildDocker
on: [push]
jobs:
  build:
    runs-on: ["self-hosted", "linux", "stroppy"]
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        working-directory: third_party/stroppy-test-cartridge
        run: ./deps.sh
      - name: build cartridge application
        working-directory: third_party/stroppy-test-cartridge
        run: cartridge build
      - name: Get latest tag
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - run: id -u && id -g
      - name: build docker image
        working-directory: third_party/stroppy-test-cartridge
        run: cartridge pack docker --tag ghcr.io/stroppy-test-cartridge:${{ env.GIT_TAG }}
      - name: push image
        run: docker push ghcr.io/stroppy-test-cartridge:${{ env.GIT_TAG }}

