name: BuildDocker
on: [push]
jobs:
  build:
    runs-on: ["self-hosted", "linux", "stroppy"]
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        working-directory: third_party/stroppy-test-cartridge
        run: ./deps.sh
      - name: build cartridge application
        working-directory: third_party/stroppy-test-cartridge
        run: cartridge build
#      - name: Get latest tag
#        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: build docker image
        working-directory: third_party/stroppy-test-cartridge
        run: cartridge pack docker --tag docker.io/picodata/stroppy-test-cartridge:latest
#      - name: tag image as latest
#        run: docker tag docker.io/stroppy-test-cartridge:${{ env.GIT_TAG }} docker.io/stroppy-test-cartridge:latest
      - name: push image
        run: docker push docker.io/picodata/stroppy-test-cartridge:latest

