name: Synchronization
on: [push]
jobs:
  synchronization:
    runs-on: ["self-hosted", "linux", "stroppy"]
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PUSH_PRIVATE_KEY }}
      - name: Commit files
        run: |
          ssh-keyscan -H git.picodata.io >> ~/.ssh/known_hosts
          git fetch --unshallow old
          git remote set-url --push origin git@git.picodata.io:picodata/picodata/stroppy.git
          git push

