name: Synchronization
on:
  schedule:
    - cron: '5 * * * *'
jobs:
  synchronization:
    runs-on: ["self-hosted", "linux", "stroppy"]
    steps:
      - uses: actions/checkout@v2
      - name: Commit files
        run: |
          eval $(ssh-agent -s)
          echo "$PUSH_PRIVATE_KEY" | ssh-add -
          git remote set-url --push git@github.com:picodata/stroppy.git
          git push
          ssh-agent -k
